name: "Horusec Debug Security Scan"
description: "Runs Horusec with debug mode and forces JSON extraction"

runs:
  using: "composite"
  steps:
    - name: Install Horusec CLI
      run: |
        echo "Installing Horusec CLI..."
        curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/master/deployments/scripts/install.sh | bash -s latest
      shell: bash

    - name: Check Horusec Version
      run: |
        echo "Horusec version:"
        horusec version
      shell: bash

    - name: Debug Run - Raw Output
      run: |
        echo "Running Horusec in DEBUG MODE..."
        echo "-----------------------------------"

        # Ejecutar Horusec mostrando TODO el output posible
        # SIN redirecciones para ver EXACTAMENTE qué imprime
        horusec start -p . \
          --return-error=false \
          --verbose \
          --disable-docker=true \
          -o json \
          --config-file-path=horusec-config.json || true
      shell: bash

    - name: Second Run - Capture JSON
      run: |
        echo ""
        echo "-----------------------------------"
        echo "Forcing JSON capture"
        echo "-----------------------------------"

        # Capturamos TODO en un archivo para inspeccionarlo
        horusec start -p . \
          --return-error=false \
          --verbose \
          --disable-docker=true \
          -o json \
          --config-file-path=horusec-config.json \
          > horusec-report.json 2>&1 || true

        echo "Finished capturing output"
      shell: bash

    - name: Show raw JSON file
      run: |
        echo ""
        echo "-----------------------------------"
        echo "Raw horusec-report.json content"
        echo "-----------------------------------"
        cat horusec-report.json || echo "File not found"
      shell: bash

    - name: Parse JSON vulnerabilities
      run: |
        echo ""
        echo "-----------------------------------"
        echo "Parsed Vulnerabilities"
        echo "-----------------------------------"

        # Intentamos parsear JSON aunque esté sucio
        jq -r '
          try .analysisVulnerabilities[]?.vulnerability as $v
          | "\($v.severity) | \($v.file):\($v.line) | \($v.details)"
        ' horusec-report.json \
        || echo "Could not parse vulnerabilities (file may not be JSON)"
      shell: bash

