name: "Horusec Security Scan"
description: "Runs Horusec analysis with config file"

runs:
  using: "composite"
  steps:
    - name: Install Horusec CLI
      run: |
        curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/master/deployments/scripts/install.sh | bash -s latest
      shell: bash

    - name: Run Horusec
      run: |
        horusec start -p . \
          --config-file-path=horusec-config.json \
          --return-error=true
      shell: bash

