name: "Horusec Security Scan"
description: "Runs Horusec analysis with config file"

runs:
  using: "composite"
  steps:
    - name: Install Horusec CLI
      run: |
        curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/master/deployments/scripts/install.sh | bash -s latest
      shell: bash

    - name: Run Horusec and Show Vulnerabilities
      run: |
        # Ejecuta Horusec y guarda el reporte JSON
        horusec start -p . \
          --config-file-path=horusec-config.json \
          -o json \
          --show-vulnerabilities-types="Vulnerability" \
          --return-error=false > horusec-report.json

        # Mostrar vulnerabilidades en consola de forma legible
        echo "Vulnerabilities found:"
        jq -r '.analysisVulnerabilities[] | 
          .vulnerabilities | 
          "\(.severity) - \(.file):\(.line) - \(.details)"' horusec-report.json
      shell: bash

